name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyTest:
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: pip install pytest
      - name: Checkout py-mms
        uses: actions/checkout@v2
      - name: Run Tests
        run: pytest -v
